export const Students = [
  { name: "Nur", level: "undergrad", status: "Student" },
  { name: "Nur", level: "undergrad", status: "Student" },
  { name: "Nur", level: "undergrad", status: "Student" },
  { name: "Nur", level: "undergrad", status: "Student" },
  { name: "Nur", level: "undergrad", status: "Student" },
  { name: "Nur", level: "undergrad", status: "Student" },
  { name: "Nur", level: "undergrad", status: "Student" },
  { name: "Nur", level: "undergrad", status: "Student" },
  { name: "Nur", level: "undergrad", status: "Student" },
  { name: "Nur", level: "undergrad", status: "Student" },
  { name: "Nur", level: "undergrad", status: "Student" },
  { name: "Nur", level: "undergrad", status: "Student" },
  { name: "Nur", level: "undergrad", status: "Student" },
  { name: "Nur", level: "undergrad", status: "Student" },
  { name: "Nur", level: "undergrad", status: "Student" },
  { name: "Nur", level: "undergrad", status: "Student" },
  { name: "Nur", level: "undergrad", status: "Student" },
];
